In [ ]:
#Implementing a Random Forest Classifier

In [10]:
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np
import cv2
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
x_train.shape,x_test.shape
# Normalization
x_train = x_train/255.0
x_test = x_test/255.0
#sklearn expects i/p to be 2d array-model.fit(x_train,y_train)=>reshape to 2d array
nsamples, nx, ny, nrgb = x_train.shape
x_train2 = x_train.reshape((nsamples,nx*ny*nrgb))
#so,eventually,model.predict() should also be a 2d input
nsamples, nx, ny, nrgb = x_test.shape
x_test2 = x_test.reshape((nsamples,nx*ny*nrgb))

#For this, we must first import it from sklearn:
from sklearn.ensemble import RandomForestClassifier
#Create an instance of the RandomForestClassifier class:
model=RandomForestClassifier()
#Finally, let us proceed to train the model:
model.fit(x_train2,y_train)

<ipython-input-10-a8fd2310e724>:23: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x_train2,y_train)


RandomForestClassifier()

In [27]:
#Now, predict for the test set using the fitted Random Forest Classifier model:

y_pred=model.predict(x_test2)
y_pred
# Now, evaluate the model with the test images by obtaining its classification report, confusion matrix, and accuracy score.

accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test))
confusion_matrix(y_pred,y_test)
# Option 1: Raw string with 'r' prefix
img_path = '/bird.jfif'



img_arr = cv2.imread(img_path)
img_arr = cv2.resize(img_arr, (32, 32))
#Now, reshape the image to 2D as discussed in the pre-processing section:

#so,eventually,model.predict() should also be a 2d input
nx, ny, nrgb = img_arr.shape
img_arr2 = img_arr.reshape(1,(nx*ny*nrgb))
#Let us declare a list called classes:

classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]
ans=model.predict(img_arr2)
print(classes[ans[0]])
#RandomForestClassifier


              precision    recall  f1-score   support

           0       0.56      0.54      0.55      1041
           1       0.54      0.52      0.53      1021
           2       0.35      0.40      0.37       867
           3       0.28      0.35      0.31       803
           4       0.40      0.39      0.39      1024
           5       0.39      0.43      0.41       905
           6       0.57      0.46      0.51      1227
           7       0.46      0.52      0.49       879
           8       0.61      0.57      0.59      1059
           9       0.55      0.47      0.51      1174

    accuracy                           0.47     10000
   macro avg       0.47      0.47      0.47     10000
weighted avg       0.48      0.47      0.47     10000

bird


In [ ]:
#Implementing a KNN

In [13]:
from sklearn.neighbors import KNeighborsClassifier
#and then instantiating it to create a KNN model:

knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train2,y_train)
#Now, predict for the test set using the fitted KNN model:

y_pred_knn=knn.predict(x_test2)
y_pred_knn
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))
confusion_matrix(y_pred_knn,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


              precision    recall  f1-score   support

           0       0.52      0.40      0.45      1299
           1       0.20      0.70      0.30       280
           2       0.44      0.22      0.29      2013
           3       0.20      0.28      0.23       707
           4       0.52      0.23      0.32      2222
           5       0.20      0.40      0.27       504
           6       0.27      0.35      0.30       761
           7       0.20      0.70      0.31       281
           8       0.69      0.39      0.50      1749
           9       0.14      0.73      0.23       184

    accuracy                           0.34     10000
   macro avg       0.34      0.44      0.32     10000
weighted avg       0.45      0.34      0.35     10000



array([[518, 118, 110,  66,  60,  63,  22,  78, 112, 152],
       [  7, 195,   2,   5,   0,   2,   1,   8,  10,  50],
       [118, 124, 437, 243, 268, 225, 271, 185,  47,  95],
       [ 12,  51,  50, 199,  33, 156,  56,  57,  34,  59],
       [ 46, 173, 250, 214, 521, 201, 319, 294,  69, 135],
       [  5,  32,  24, 102,  14, 204,  32,  60,  12,  19],
       [ 30,  55,  65, 108,  44,  80, 265,  48,  14,  52],
       [  5,   8,   7,  11,  11,  10,   1, 196,   7,  25],
       [255, 223,  53,  51,  48,  53,  32,  68, 688, 278],
       [  4,  21,   2,   1,   1,   6,   1,   6,   7, 135]])

In [ ]:
#Implementing a Decision Tree

In [15]:
from sklearn.tree import DecisionTreeClassifier
#and then instantiating it to create a DecisionTreeClassifier model:

dtc=DecisionTreeClassifier()
#Finally, train it:

dtc.fit(x_train2,y_train)
#Now, predict for the test set using the fitted decision tree model:

y_pred_dtc=dtc.predict(x_test2)
y_pred_dtc
accuracy_score(y_pred_dtc,y_test)
print(classification_report(y_pred_dtc,y_test))
confusion_matrix(y_pred_dtc,y_test)

              precision    recall  f1-score   support

           0       0.36      0.34      0.35      1065
           1       0.28      0.29      0.29       948
           2       0.21      0.20      0.20      1069
           3       0.19      0.19      0.19       980
           4       0.24      0.24      0.24       990
           5       0.22      0.22      0.22      1022
           6       0.27      0.29      0.28       929
           7       0.27      0.28      0.27       974
           8       0.38      0.37      0.37      1042
           9       0.29      0.29      0.29       981

    accuracy                           0.27     10000
   macro avg       0.27      0.27      0.27     10000
weighted avg       0.27      0.27      0.27     10000



array([[364,  66, 104,  62,  63,  54,  43,  83, 148,  78],
       [ 70, 279,  51,  57,  45,  61,  49,  76,  99, 161],
       [ 88,  77, 210, 118, 153, 104, 133,  87,  49,  50],
       [ 55,  80,  92, 188,  86, 157, 115,  85,  44,  78],
       [ 51,  59, 133, 103, 242,  83, 145,  90,  46,  38],
       [ 52,  46, 137, 128, 112, 221, 102, 109,  54,  61],
       [ 37,  56,  97, 120, 110,  92, 270,  59,  28,  60],
       [ 48,  62,  88, 100, 105, 106,  69, 270,  47,  79],
       [159, 110,  41,  58,  38,  60,  24,  62, 381, 109],
       [ 76, 165,  47,  66,  46,  62,  50,  79, 104, 286]])

In [ ]:
#Implementing a Naive Bayes classifier

In [16]:
from sklearn.naive_bayes import GaussianNB
#and then instantiating it to create an NB model:

nb=GaussianNB()
#Finally, train it:

nb.fit(x_train2,y_train)
#Now, predict for the test set using the fitted NB model:

y_pred_nb=nb.predict(x_test2)
y_pred_nb
accuracy_score(y_pred_nb,y_test)
print(classification_report(y_pred_nb,y_test))
confusion_matrix(y_pred_nb,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.49      0.27      0.35      1817
           1       0.17      0.41      0.24       405
           2       0.08      0.19      0.12       443
           3       0.08      0.25      0.12       305
           4       0.42      0.24      0.30      1737
           5       0.26      0.31      0.29       840
           6       0.47      0.25      0.33      1846
           7       0.13      0.42      0.20       310
           8       0.47      0.39      0.42      1219
           9       0.41      0.38      0.39      1078

    accuracy                           0.30     10000
   macro avg       0.30      0.31      0.28     10000
weighted avg       0.39      0.30      0.32     10000



array([[494, 141, 225, 163,  86, 156, 106, 134, 168, 144],
       [ 20, 166,  24,  36,   8,  17,   2,  24,  41,  67],
       [ 39,  24,  83,  54,  57,  55,  60,  36,  18,  17],
       [ 10,  31,  15,  76,  26,  51,  18,  41,  17,  20],
       [ 84,  66, 292, 151, 417, 167, 228, 228,  56,  48],
       [ 34,  72,  48, 129,  38, 264,  46,  94,  83,  32],
       [ 50, 192, 209, 262, 265, 159, 467, 102,  39, 101],
       [  9,  19,  21,  26,  22,  36,  15, 131,   8,  23],
       [200, 121,  54,  34,  50,  57,  19,  72, 471, 141],
       [ 60, 168,  29,  69,  31,  38,  39, 138,  99, 407]])